//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LjcWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class word_tb
    {
        [Key]
        public long WordId { get; set; }
        public string Spelling { get; set; }
        public string Phonetic { get; set; }
        public string Paraphrase { get; set; }
        public int Process { get; set; }
        public int Priority { get; set; }
        public Nullable<System.DateTime> LastLearn { get; set; }
        public Nullable<System.DateTime> FirstLearn { get; set; }
        public System.DateTime Import { get; set; }
        public string Classs { get; set; }
        public Nullable<bool> IsRemembered { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.DateTime> LastLearnBackup { get; set; }
        public int LastProcess { get; set; }
        public Nullable<int> LastForget { get; set; }
        public int YesTotalCount { get; set; }
        public int NoTotalCount { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<long> ExpireSpanTicks { get; set; }
        /// <summary>
        /// 隐藏项（0随机 1隐藏解释 2隐藏拼写）
        /// </summary>
        public int HideItem { get; set; }
    }
}
